config/routes.rb
FreshList::Application.routes.draw do

  devise_for :users

  resources :users do
    resources :preferences
    resources :recipes
  end

  resources :recipes do
    collection do
        patch 'update_multiple'
    end
  end

  root to: "users#show"

end

app/models/recipe.rb
require 'net/http'
class Recipe < ActiveRecord::Base

  validates :name, presence: true, uniqueness: {case_sensistive: false}
  validates :image, presence: true
  validates :carbs, presence: true
  validates :protein, presence: true
  validates :fats, presence: true
  validates :url, presence: true

  has_many :user_recipes
  has_many :users, through: :user_recipes, source: :user

  class << self
    def search(search)
      search = search.downcase
      results = all.where('to_tsvector(name) @@ plainto_tsquery(?)', search)

      # if the database doesnt include the search term we are going to query the yummly api
      if results.map {|x| x[:name].downcase.include? search}.include? true
        return results
      else
        clean(search)
      end
    end

    # we need to make sure the data is in the right format for the search
    def clean(search)
      if search.include? ' '
        params = search.split(' ').join('+')
      else
        params = search
      end
      yummly_recipes(params, search)
    end

    # this next block is going to search recipes and return 10 recipes that match our search
    def yummly_recipes(params, search)
      source = 'http://api.yummly.com/v1/api/recipes?_app_id=76673592&_app_key=17ee3cd3288f06af85bc442278910238&q=' + params + '&requirePictures=true'
      resp = Net::HTTP.get_response(URI.parse(source))
      data = resp.body
      recipes = JSON.parse(data)
      if recipes["matches"].length == 0
        return "No Recipes Found"
      else
        yummly_ingredients(recipes, search)
      end
    end

    # this next block then queries the yummly api again to get more data including nutritional info from the api for each recipe
    def yummly_ingredients(recipes, search)
      recipes["matches"].each do |plate|
        recipe_id = plate["id"]
        source = 'http://api.yummly.com/v1/api/recipe/' + recipe_id + '?_app_id=76673592&_app_key=17ee3cd3288f06af85bc442278910238&'
        resp = Net::HTTP.get_response(URI.parse(source))
        data = resp.body
        info = JSON.parse(data)
        new_recipe(info, plate)
      end
      search(search)
    end

    #i need to look up a more graceful way of creating new objects
    def new_recipe(info, plate)
      recipe = Recipe.new
      recipe.name = plate["recipeName"]
      recipe.image = plate["imageUrlsBySize"]["90"]
      recipe.url = 'http://www.yummly.com/recipe/' + plate["id"]
      nutrition_estimates(info, recipe)
    end

    # this next block returns carbs protein and fats in grams
    def nutrition_estimates(info, recipe)
      info["nutritionEstimates"].each do |attribute|
        if attribute["description"] == 'Carbohydrate, by difference'
          recipe.carbs = attribute["value"].round(0)
        end
        if attribute["description"] == 'Protein'
          recipe.protein = attribute["value"].round(0)
        end
        if attribute["description"] == 'Total lipid (fat)'
          recipe.fats = attribute["value"].round(0)
        end
      end
      recipe.save
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @user = current_user
    @recipes = []
    searches = current_user.preferences.map{|x| x[:name]}.uniq
    searches.each do |search|
      @recipes << Recipe.search(search)
    end
    @recipes
  end

  def show
    @recipe = Recipe.find(params["id"])
  end

  def edit
    binding.pry
    @recipe = Recipe.find(params["id"])
  end

  def update_multiple
    params["ids"].each do |id|
      recipe = Recipe.find(id)
      current_user.recipes << recipe
    end
    redirect_to user_path(current_user), notice: "Recipes Saved"
  end



  def private
    params.require(:recipes).permit(:user)
  end
end

app/views/recipes/index.html.erb
<div class = "display" >
  <div class = "show-recipe panel clearfix">
    <h2 class= "recipe-index">Recipes: Powered by Yummly</h2>

    <% if @recipes %>
      <%= form_tag update_multiple_recipes_path, method: :patch do %>
        <div class = "body grid-container">
          <% @recipes.each do |preference|%>
            <% preference.each do |recipe| %>
              <div class = "recipe grid-3">
                <h5><a class = "recipe-tag" href = <%= recipe[:url] %> ><%= recipe[:name] %></a></h5>
                <div><img class = "index" src = <%= recipe[:image] %> alt='no image'></div>
                <ul class = "info">
                  <li>Fats: <%= recipe[:fats].round(0) %> grams</li>
                  <li>Protein: <%= recipe[:protein].round(0) %> grams</li>
                  <li>Carbs: <%= recipe[:carbs].round(0) %> grams</li>
                  <li><%= check_box_tag "ids[]", recipe.id %><%= label_tag("add to cart") %></li>
                </ul>
              </div>
            <% end %>
          <% end %>
      <div class = "row"
        <div class = "large-centered large-8 columns">
        <%= submit_tag "Keep Recipes", class: "button submit-recipes" %>
      </div>
    </div>
      <% end %>
    <% end %>
  </div>
</div>